/**
 * Data Engine Intake Result
 *
 * Output of intake evaluation.
 * Represents the deterministic decision made by the intake layer.
 */

import type { DataEngineIntakeStatus } from '../types/DataEngineIntakeStatus';
import type { DataEngineIntakeIssue } from './DataEngineIntakeIssue';
import type { DataEngineIntakePolicy } from './DataEngineIntakePolicy';

/**
 * Intake Result model.
 *
 * Produced by evaluateFeedIntake().
 * Fully describes the intake decision and reasoning.
 *
 * Design principle:
 * The result is complete, auditable, and deterministic.
 * All decision factors are visible in the result structure.
 * No hidden logic or side effects.
 */
export interface DataEngineIntakeResult {
  /**
   * Intake decision status.
   * The final determination of what happens to this candidate.
   */
  readonly status: DataEngineIntakeStatus;

  /**
   * Issues encountered during evaluation.
   * Empty array = no issues (status likely ACCEPTED).
   * Non-empty array = issues exist (may still be accepted if allowed by policy).
   */
  readonly issues: DataEngineIntakeIssue[];

  /**
   * Candidate identifier (for traceability).
   * Links this result back to the evaluated candidate.
   */
  readonly candidateId: string;

  /**
   * Feed envelope reference (optional).
   * If accepted, reference to the resulting DataEngineFeedEnvelope.
   * Not generated by intake layer; provided by downstream system if applicable.
   *
   * Example: 'feed_svc_20260311_001a8f9e'
   */
  readonly feedEnvelopeRef?: string;

  /**
   * Policy applied during evaluation.
   * The exact policy used to make this decision.
   * Enables auditing, policy version tracking, and decision reproducibility.
   */
  readonly policyApplied: DataEngineIntakePolicy;

  /**
   * Human-readable decision summary.
   * Brief explanation of why the intake decision was made.
   *
   * Examples:
   * - "Feed accepted with 2 warnings (legacy conformance, missing region)"
   * - "Feed rejected: missing required identityId"
   * - "Feed quarantined: malformed timestamp requires manual review"
   */
  readonly decisionSummary: string;

  /**
   * When this evaluation occurred.
   * ISO 8601 UTC timestamp.
   * Enables intake result history and reasoning audit trails.
   */
  readonly evaluatedAt: string;
}
