export enum GraphIndexType {
  NODE_INDEX = 'NODE_INDEX',
  EDGE_INDEX = 'EDGE_INDEX',
  TEMPORAL_INDEX = 'TEMPORAL_INDEX',
  INTELLIGENCE_INDEX = 'INTELLIGENCE_INDEX',
  LINEAGE_INDEX = 'LINEAGE_INDEX',
  TRUST_INDEX = 'TRUST_INDEX',
}
