export enum ContextEdgeType {
  OCCURRED_IN_DOMAIN = 'OCCURRED_IN_DOMAIN',
  ASSOCIATED_WITH_CONTEXT = 'ASSOCIATED_WITH_CONTEXT',
  SCOPED_TO_WORKFLOW = 'SCOPED_TO_WORKFLOW',
  SCOPED_TO_ORGANIZATION = 'SCOPED_TO_ORGANIZATION',
  SCOPED_TO_USE_CASE = 'SCOPED_TO_USE_CASE',
}
