export enum FederationEdgeType {
  LINKED_TO_FLEET_GRAPH = 'LINKED_TO_FLEET_GRAPH',
  LINKED_TO_SERVICE_NETWORK = 'LINKED_TO_SERVICE_NETWORK',
  LINKED_TO_MARKET_VIEW = 'LINKED_TO_MARKET_VIEW',
  LINKED_TO_PARTNER_DOMAIN = 'LINKED_TO_PARTNER_DOMAIN',
  FEDERATED_WITH_EXTERNAL_GRAPH = 'FEDERATED_WITH_EXTERNAL_GRAPH',
}
