export enum IntelligenceEdgeType {
  DERIVED_FROM_EVENT = 'DERIVED_FROM_EVENT',
  DERIVED_FROM_SOURCE = 'DERIVED_FROM_SOURCE',
  CORRELATED_WITH_INTELLIGENCE = 'CORRELATED_WITH_INTELLIGENCE',
  ATTACHED_TO_CONTEXT = 'ATTACHED_TO_CONTEXT',
  ATTACHED_TO_TIMELINE = 'ATTACHED_TO_TIMELINE',
}
