export enum ProvenanceEdgeType {
  INGESTED_FROM_SOURCE = 'INGESTED_FROM_SOURCE',
  DERIVED_FROM_NODE = 'DERIVED_FROM_NODE',
  GENERATED_BY_PROCESS = 'GENERATED_BY_PROCESS',
  TRACED_TO_RECORD = 'TRACED_TO_RECORD',
  LINKED_TO_LINEAGE = 'LINKED_TO_LINEAGE',
}
