export enum TrustEdgeType {
  ASSERTED_BY_SOURCE = 'ASSERTED_BY_SOURCE',
  CONFIRMED_BY_PROCESS = 'CONFIRMED_BY_PROCESS',
  SUPPORTED_BY_EVIDENCE = 'SUPPORTED_BY_EVIDENCE',
  CONTRADICTED_BY_NODE = 'CONTRADICTED_BY_NODE',
  TRUST_PROPAGATED_FROM = 'TRUST_PROPAGATED_FROM',
}
