/**
 * PartMaster - Canonical Single Source of Truth for Parts Ecosystem
 * Used by: Aftermarket, B2B Network, Stock Signals, Risk Analysis, Data Engine
 */

// ========== CANONICAL MODELS (Part Master Core) ==========

/**
 * PartMasterPart: The canonical representation of a part
 * Every field is immutable after creation (except lastUpdated for price/availability)
 */
export interface PartMasterPart {
  partMasterId: string;         // UUID - eternal identifier
  tenantId: string;             // Multi-tenant
  
  // Identification
  sku: string;                  // Unique within tenant
  name: string;
  description?: string;
  
  // Taxonomy
  category: PartCategory;
  partGroup?: string;           // e.g., "Brake System", "Powertrain"
  
  // Quality & Brand
  qualityTier: QualityTier;     // OEM | PREMIUM | EQUIVALENT | ECONOMY
  brand: Brand;
  
  // Cross-references
  oemRefs: OemRef[];            // 1..many
  aftermarketRefs: AftermarketRef[];  // Equivalent parts
  
  // Fitment
  fitments: Fitment[];          // Compatible vehicles
  
  // Physical metadata
  unit: 'adet' | 'litre' | 'set' | 'metre' | 'kg';
  packSize: number;
  weight?: number;
  
  // OEM Canonicalization (for master catalog ingestion)
  oem_source?: {
    brand: string;              // Source OEM brand
    part_number: string;        // Original OEM PN
    catalog_date?: string;      // When ingested from catalog
  };
  canonical_hash?: string;      // Hash of (oem_brand + normalized_pn) for dedup
  quality_default?: 'OEM' | 'OES' | 'AFTERMARKET_A' | 'AFTERMARKET_B';  // Default when none specified
  mapping_status?: 'AUTO' | 'REVIEW' | 'APPROVED' | 'REJECTED';  // Workflow status
  mapping_id?: string;          // Link to OemAftermarketMap
  
  // Audit trail
  createdAt: string;
  updatedAt: string;
  createdBy?: string;
  dataQuality?: number;         // 0-100: how trusted is this record
}

export type QualityTier = 'OEM' | 'PREMIUM' | 'EQUIVALENT' | 'ECONOMY';

export interface Brand {
  brandId: string;
  name: string;
  origin?: string;              // e.g., "Germany", "Turkey"
  tier?: 'OEM' | 'AFTERMARKET';
  reliability?: number;         // 0-100
}

export interface OemRef {
  refId: string;
  oemCode: string;              // e.g., "BMW-34-25-6761671"
  brand: string;                // OEM brand
  vehicleFitment?: string;      // Platform code
  confidence?: number;          // 0-100
}

export interface AftermarketRef {
  refId: string;
  brand: string;                // Aftermarket brand
  sku: string;
  qualityTier: QualityTier;
  priceRelative?: number;       // 1.0 = same as OEM, 0.5 = 50% cheaper
  availability?: 'AVAILABLE' | 'SCARCE' | 'DISCONTINUED';
}

// ========== OEM CANONICALIZATION MODELS ==========

/**
 * OemCatalogItem: Raw OEM part from manufacturer catalog
 * Source of truth for original equipment specifications
 */
export interface OemCatalogItem {
  id: string;                               // Unique within catalog load
  oem_brand: string;                        // BMW, Volkswagen, Ford, etc.
  oem_part_number: string;                  // Manufacturer part number (e.g., "34 11 6 789 123")
  part_name: string;                        // e.g., "Brake Pad Front Left"
  category: string;                         // e.g., "BRAKE_SYSTEM", "FILTERS"
  
  // Vehicle fitment
  vehicle_fitment?: Array<{
    make: string;                           // BMW
    model: string;                          // 320i
    year_from: number;
    year_to: number;
    engine?: string;                        // 2.0L
    transmission?: string;                  // Manual, Automatic
  }>;
  
  // Physical attributes
  attributes?: Record<string, string>;      // measurement, diameter, thread, capacity, etc.
  
  // Supersession tracking
  superseded_by?: string;                   // If obsolete, which part replaces it
  
  // Metadata
  source: 'API' | 'MANUAL' | 'BULK_UPLOAD';
  last_updated: string;                     // ISO timestamp
}

/**
 * AftermarketCandidate: Potential aftermarket equivalent of an OEM part
 * Generated by matching engine or human validation
 */
export interface AftermarketCandidate {
  candidate_id: string;
  brand: string;                            // Bosch, Mann, Brembo, NGK, Valeo, etc.
  aftermarket_part_number: string;          // Supplier part number
  quality_grade: 'OEM' | 'OES' | 'AFTERMARKET_A' | 'AFTERMARKET_B';
  
  // Matching confidence
  confidence: number;                       // 0-100: how certain is this match
  evidence: string[];                       // Reasons for match (e.g., "name_similarity", "dimension_match", "crossref_database")
  
  // Attributes (should align with OEM)
  matched_attributes?: Record<string, string>;
}

/**
 * OemAftermarketMap: Mapping between one Oem part and its aftermarket candidates
 * Updated by detectAftermarketCandidates() and manual validation
 */
export interface OemAftermarketMap {
  map_id: string;                           // UUID
  oem_part_number: string;                  // Link back to OEM
  oem_brand: string;
  canonical_part_master_id: string;         // PM-XXXX (links to PartMasterPart)
  
  // Candidates
  matches: AftermarketCandidate[];          // 0..many aftermarket options
  
  // Status workflow
  status: 'AUTO' | 'REVIEW' | 'APPROVED' | 'REJECTED';
  reason?: string;                          // Why REVIEW or REJECTED
  reviewed_by?: string;                     // User who approved/rejected
  reviewed_at?: string;                     // ISO timestamp
  
  // Metadata
  created_at: string;
  updated_at: string;
  confidence_threshold: number;             // Min confidence to include matches
}

/**
 * SupplierOffer: Bridge between Part Master and B2B Network
 * A supplier's specific pricing/availability for a part
 */
export interface SupplierOffer {
  offerId: string;
  supplierId: string;
  supplierName: string;
  partMasterId: string;         // Reference to PartMasterPart
  
  // Pricing
  price: number;
  currency: 'USD' | 'EUR' | 'TRY';
  minOrderQty: number;
  packQty?: number;
  
  // Availability
  stock: number;
  leadDays: number;
  lastUpdated: string;
  
  // Quality assurance
  isVerified: boolean;
  trustScore?: number;          // 0-100
}

/**
 * PriceSnapshot: Historical price data for analytics
 */
export interface PriceSnapshot {
  snapshotId: string;
  partMasterId: string;
  date: string;
  price: number;
  currency: string;
  source: 'OEM' | 'B2B' | 'MARKET';
}

/**
 * StockSnapshot: Historical stock data
 */
export interface StockSnapshot {
  snapshotId: string;
  partMasterId: string;
  date: string;
  onHand: number;
  reserved: number;
  inTransit: number;
}

/**
 * LeadTimeSnapshot: Track lead time trends
 */
export interface LeadTimeSnapshot {
  snapshotId: string;
  supplierId: string;
  partMasterId: string;
  date: string;
  leadDays: number;
  expedited?: number;
}

/**
 * TenantPriceRule: Masking/visibility rules per tenant
 */
export interface TenantPriceRule {
  ruleId: string;
  tenantId: string;
  minVisibility: 'ADMIN' | 'MANAGER' | 'PUBLIC';
  markup?: number;              // 1.2 = 20% markup
  discount?: number;            // 0.1 = 10% discount
  visibleQualityTiers: QualityTier[];
}

/**
 * PurchasePolicy: Strategy for ordering
 */
export interface PurchasePolicy {
  policyId: string;
  partMasterId: string;
  tenantId: string;
  
  preferredSupplier?: string;
  targetStockDays?: number;     // Reorder point = demand * targetStockDays
  maxStockDays?: number;
}

/**
 * SupplierPriceFeed: Real-time price and stock updates from supplier feeds
 * Replaces manual seed - enables dynamic pricing from APIs, SFTP, etc.
 * 
 * Feed sync rules:
 * - valid_until < now → offer not purchasable
 * - stock_on_hand = 0 → can show but not best offer
 * - Latest record per (supplier_id, part_master_id) wins
 */
export interface SupplierPriceFeed {
  id: string;
  supplier_id: string;
  supplier_name: string;
  part_master_id: string;
  supplier_part_number: string;
  
  // Pricing (with calculations)
  currency: 'TRY' | 'EUR' | 'USD';
  list_price: number;           // Base price
  discount_pct: number;         // 0-100, applied to list_price
  freight_cost: number;         // Added to final cost
  effective_price?: number;     // list_price * (1 - discount_pct/100) + freight_cost
  
  // Stock & Lead Time
  stock_on_hand: number;
  lead_time_days: number;
  
  // Feed metadata
  valid_from: string;           // ISO timestamp
  valid_until: string;          // ISO timestamp - CRITICAL for purchasability
  last_sync_at: string;         // When was this synced from source
  source: 'API' | 'SFTP' | 'MANUAL';
  
  // Status
  is_active: boolean;           // Soft delete
  quality_grade: 'OEM' | 'OES' | 'AFTERMARKET_A' | 'AFTERMARKET_B';
}

/**
 * OrderIntent: Signals what consumer (Aftermarket, Bakım Merkezi, etc) wants
 */
export interface OrderIntent {
  intentId: string;
  partMasterId: string;
  consumer: 'AFTERMARKET' | 'MAINTENANCE_CENTER' | 'INDIVIDUAL' | 'FLEET' | 'INSURANCE';
  quantity: number;
  urgency: 'STANDARD' | 'EXPEDITED' | 'EMERGENCY';
  createdAt: string;
}

// ========== CORE ENTITIES ==========

export interface Part {
  partId: string;           // UUID or stable key
  sku: string;              // Unique within tenant
  name: string;
  brand?: string;
  description?: string;
  category: PartCategory;
  subcategory?: string;
  
  // Cross-references
  oemRefs: string[];        // OEM part numbers
  crossRefs: string[];      // Equivalent aftermarket parts
  
  // Physical properties
  unit: 'adet' | 'litre' | 'set' | 'metre' | 'kg';
  packSize: number;
  weight?: number;          // kg
  dimensions?: string;      // cm or JSON
  
  // Status & Source
  status: 'ACTIVE' | 'INACTIVE' | 'DISCONTINUED';
  source: 'ERP' | 'EXCEL' | 'MANUAL' | 'B2B' | 'MOCK';
  
  // Audit
  createdAt: string;
  updatedAt: string;
  createdBy?: string;
  updatedBy?: string;
}

export type PartCategory = 
  | 'POWERTRAIN'       // Motor, şanzıman, viskoplatin
  | 'TRANSMISSION'     // Manual, Otomatik, CVT
  | 'ELECTRONIC'       // Sensörler, ECU, batarya
  | 'BODY'             // Şasi, kapı, cam
  | 'COOLING'          // Radiator, su pompası
  | 'FUEL'             // Yakıt sistemi
  | 'BRAKE'            // Fren sistemi
  | 'SUSPENSION'       // Amortisör, yatak
  | 'LIGHTING'         // Far, arka lamba
  | 'INTERIOR'         // Döşeme, tabela
  | 'AFTERMARKET'      // Aksesuar, sarf malzeme
  | 'OTHER';

export interface Supplier {
  supplierId: string;
  name: string;
  type: 'WHOLESALER' | 'DISTRIBUTOR' | 'MANUFACTURER' | 'B2B_NETWORK';
  contactPerson?: string;
  email?: string;
  phone?: string;
  address?: string;
  country?: string;
  
  // Performance metrics
  avgLeadDays?: number;
  reliabilityScore?: number;  // 0-100
  priceCompetitiveness?: number;
  
  status: 'ACTIVE' | 'INACTIVE';
  createdAt: string;
  updatedAt: string;
}

export interface SupplierPartEdge {
  edgeId: string;
  supplierId: string;
  partId: string;
  
  // Pricing & Supply
  supplierSku?: string;
  unitPrice: number;
  currency: 'USD' | 'EUR' | 'TRY';
  minOrderQty: number;
  packQty?: number;
  
  // Lead time
  leadDays: number;           // Standard delivery
  expeditedLeadDays?: number;
  
  // Status
  active: boolean;
  lastUpdated: string;
  
  // Audit
  createdAt: string;
  updatedAt: string;
}

export interface InventoryItem {
  inventoryId: string;
  partId: string;
  warehouseId: string;         // or location code
  
  // Stock levels
  onHand: number;
  reserved: number;            // Already allocated
  inTransit: number;           // Ordered but not arrived
  safetyStock: number;         // Minimum required level
  maxStock?: number;
  
  // Valuation
  unitCost?: number;           // Last cost
  totalValue?: number;         // onHand * unitCost
  
  // Aging
  status: 'GOOD' | 'AGING' | 'DEAD_STOCK';
  lastMovedDate?: string;      // Last in/out activity
  
  updatedAt: string;
}

export interface SalesSignal {
  signalId: string;
  partId: string;
  period: 'D30' | 'D90' | 'D180' | 'D365';  // Last 30/90/180/365 days
  
  // Demand metrics
  soldQty: number;             // Total units sold
  soldValue?: number;          // Revenue
  avgPrice?: number;           // Average selling price
  
  // Velocity
  dailyAverage?: number;
  weeklyTrend?: 'UP' | 'DOWN' | 'STABLE';
  seasonalFactor?: number;     // 1.0 = normal
  
  // Profitability
  marginPercent?: number;
  marginTrend?: 'UP' | 'DOWN' | 'STABLE';
  
  // Risk flags
  deadStockRisk?: number;      // 0-100, >80 = critical
  forecastStock?: number;      // Projected 30-day coverage
  
  generatedAt: string;
  source?: 'ERP' | 'MANUAL' | 'ESTIMATED' | 'MOCK';
}

export interface PriceSignal {
  signalId: string;
  partId: string;
  
  // Price tracking
  lastUnitPrice: number;
  avgPrice30d?: number;
  minPrice30d?: number;
  maxPrice30d?: number;
  
  // Volatility
  volatilityPercent?: number;  // 0-100
  trend?: 'UP' | 'DOWN' | 'STABLE';
  
  // Masking for KVKK
  masked: boolean;             // If true, price hidden from certain roles
  maskedReason?: 'CONFIDENTIAL' | 'CUSTOMER_SPECIFIC' | 'NEGOTIATED';
  
  lastUpdated: string;
  currency: 'USD' | 'EUR' | 'TRY';
}

export interface CategoryNode {
  categoryId: string;
  name: PartCategory;
  parentCategory?: PartCategory;
  description?: string;
  partCount?: number;          // Number of parts in this category
  totalStockValue?: number;    // Sum of all part values
}

export interface OEMCrossRef {
  refId: string;
  oem: string;                 // OEM code (BMW-00001)
  aftermarketId: string;       // Aftermarket part ID
  aftermarketSku: string;
  fitmentNotes?: string;
  confidence?: number;         // 0-100, match confidence
}

export interface Fitment {
  fitmentId: string;
  partId: string;
  vehiclePlatform: string;     // e.g., "BMW_F30_2012_2018"
  applicableModels?: string[];
  engineTypes?: string[];
  notes?: string;
}

// ========== AGGREGATE ROOT ==========

export interface PartMasterSnapshot {
  // Meta
  tenantId: string;
  generatedAt: string;
  expiresAt?: string;          // For cache invalidation
  source: 'REAL' | 'MOCK';
  
  // Core data collections
  parts: Part[];
  suppliers: Supplier[];
  edges: SupplierPartEdge[];
  inventory: InventoryItem[];
  salesSignals: SalesSignal[];
  priceSignals: PriceSignal[];
  categories: CategoryNode[];
  
  // Cross-reference mappings
  mappings: {
    oemCrossRefs: OEMCrossRef[];
    fitments: Fitment[];
  };
  
  // Summary statistics
  summary?: {
    totalParts: number;
    totalSuppliers: number;
    totalStockValue: number;
    totalOnHand: number;
    criticalStockCount: number;
    deadStockCount: number;
    avgTurnover30d: number;
  };
  
  // Content-type guarantee
  contentType: 'application/json';
}

// ========== SUPPLIERS & OFFERS ==========

/**
 * Supplier: Teklif veren tedarikçi (snake_case for API compatibility)
 */
export interface Supplier {
  supplier_id: string;
  name: string;
  type: 'DISTRIBUTOR' | 'RETAILER' | 'WHOLESALER' | 'OEM' | 'B2B_NETWORK';
  regions?: string[];
  rating?: number;
  avgLeadDays?: number;
  reliabilityScore?: number;
  priceCompetitiveness?: number;
  isActive: boolean;
  createdAt: string;
  updatedAt: string;
}

/**
 * SupplierOffer: Teklif (fiyat, stok, terim)
 * Source: manual entry, ERP feed, or B2B network
 */
export interface SupplierOffer {
  offer_id: string;           // UUID
  supplier_id: string;        // FK to Supplier
  part_master_id: string;     // FK to PartMasterPart
  tenantId?: string;          // Multi-tenant
  
  // Product identification
  supplier_sku: string;       // Supplier's own SKU
  brand: string;
  quality_grade: 'OEM' | 'OES' | 'AFTERMARKET_A' | 'AFTERMARKET_B';
  
  // Pricing
  currency: 'TRY' | 'EUR' | 'USD';
  list_price: number;         // Gross / catalog price
  
  // Availability
  stock_on_hand: number;
  lead_time_days: number;     // Days to deliver
  
  // Metadata
  source: 'MANUAL' | 'FEED' | 'ERP';
  updated_at: string;
  valid_until?: string;
  notes?: string;
}

/**
 * InstitutionPriceRule: Kurum bazlı fiyat kuralları
 */
export interface InstitutionPriceRule {
  rule_id: string;
  institution_id: string;     // e.g., "INST-001"
  supplier_id?: string;       // Null = all suppliers
  
  discount_pct?: number;      // e.g., 8 (8% discount)
  margin_pct?: number;
  payment_term_days?: number; // e.g., 30
  freight_flat?: number;      // Fixed freight per order (TRY)
  
  effective_from?: string;    // ISO date
  effective_to?: string;
  
  createdAt: string;
  updatedAt: string;
}

/**
 * EffectiveOffer: Computed offer with pricing + scoring
 * Used by Aftermarket, Bakım Merkezi for decision
 */
export interface EffectiveOffer extends SupplierOffer {
  institution_id: string;
  net_price: number;          // list_price - discount + freight
  
  // Scoring (0-100)
  score_total: number;
  score_price: number;
  score_lead_time: number;
  score_stock: number;
  score_quality: number;
  
  reason_badges: string[];    // e.g., ["En ucuz", "OEM", "Stok var"]
  purchasable: boolean;       // stock_on_hand > 0
  
  // Ranking context
  rankingPosition?: number;   // 1st best, 2nd best, etc.
}

/**
 * OfferRecommendation: Best + alternatives for a part
 */
export interface OfferRecommendation {
  part_master_id: string;
  institution_id: string;
  best: EffectiveOffer | null;           // Highest score, purchasable
  alternatives: EffectiveOffer[];        // Next best (max 5)
  timestamp: string;
}

// ========== INDICES (Data Engine outputs derived from PM) ==========

export interface SupplyHealthIndex {
  indexId: string;
  tenantId: string;
  generatedAt: string;
  
  // Metrics per supplier
  suppliers: Array<{
    supplierId: string;
    supplierName: string;
    score: number;              // 0-100
    avgLeadDays: number;
    reliabilityScore: number;
    volatilityScore: number;
    partCount: number;
    recentOrderCount?: number;
    onTimeDeliveryPercent?: number;
  }>;
}

export interface StockRiskIndex {
  indexId: string;
  tenantId: string;
  generatedAt: string;
  
  riskMatrix: Array<{
    partId: string;
    partSku: string;
    partName: string;
    riskLevel: 'CRITICAL' | 'HIGH' | 'MEDIUM' | 'LOW';
    riskFactors: string[];      // ['low_velocity', 'high_onhand', 'near_expiry']
    suggestedAction: string;
    daysToStockout?: number;
  }>;
}

export interface MarginOpportunityIndex {
  indexId: string;
  tenantId: string;
  generatedAt: string;
  
  opportunities: Array<{
    partId: string;
    partSku: string;
    partName: string;
    marginPercent: number;
    marginTrend: string;
    volumeSold30d: number;
    revenue30d: number;
    recommendation: string;     // e.g., "INCREASE_PRICE" | "PROMOTE" | "DISCONTINUE"
  }>;
}

export interface VelocityIndex {
  indexId: string;
  tenantId: string;
  generatedAt: string;
  
  tiers: {
    fastMovers: Array<{
      partId: string;
      partSku: string;
      daysToStockout: number;
      daysToReorder: number;
      recommendedOrderQty: number;
    }>;
    slowMovers: Array<{
      partId: string;
      partSku: string;
      lastMovedDaysAgo: number;
      currentOnHand: number;
      recommendedAction: 'HOLD' | 'DISCOUNT' | 'DISCONTINUE';
    }>;
  };
}

// ========== API RESPONSE TYPES ==========

export interface GetPartMasterSnapshotRequest {
  tenantId: string;
  category?: PartCategory;
  includeHistorical?: boolean;
}

export interface GetPartMasterSnapshotResponse {
  success: boolean;
  data?: PartMasterSnapshot;
  error?: string;
  timestamp: string;
}

export interface GetDataEngineIndicesResponse {
  success: boolean;
  data: {
    supplyHealth: SupplyHealthIndex;
    stockRisk: StockRiskIndex;
    marginOpportunity: MarginOpportunityIndex;
    velocity: VelocityIndex;
  };
  timestamp: string;
}

// ========== CONSTANTS ==========

export const PART_MASTER_MOCK: PartMasterSnapshot = {
  tenantId: 'LENT-CORP-DEMO',
  generatedAt: new Date().toISOString(),
  source: 'MOCK',
  contentType: 'application/json',
  
  parts: [
    {
      partId: 'PM-001',
      sku: 'BRAKE-FP-001',
      name: 'Fren Balatası Ön',
      brand: 'Brembo',
      category: 'BRAKE',
      subcategory: 'Pad Set',
      oemRefs: ['BMW-34-25-6-761-671', 'OEM-BRAKE-001'],
      crossRefs: ['BOSCH-BP-001', 'DELPHI-FP-001'],
      unit: 'set',
      packSize: 1,
      status: 'ACTIVE',
      source: 'MOCK',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      partId: 'PM-002',
      sku: 'OIL-FILTER-001',
      name: 'Yağ Filtresi',
      brand: 'Mann',
      category: 'POWERTRAIN',
      subcategory: 'Filters',
      oemRefs: ['BMW-11-42-8-584-233'],
      crossRefs: ['BOSCH-OF-001'],
      unit: 'adet',
      packSize: 1,
      status: 'ACTIVE',
      source: 'MOCK',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      partId: 'PM-003',
      sku: 'AIR-FILTER-001',
      name: 'Hava Filtresi',
      brand: 'Mann',
      category: 'POWERTRAIN',
      subcategory: 'Filters',
      oemRefs: [],
      crossRefs: [],
      unit: 'adet',
      packSize: 1,
      status: 'ACTIVE',
      source: 'MOCK',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      partId: 'PM-004',
      sku: 'SERPENTINE-BELT-001',
      name: 'Serpantin Kayışı',
      brand: 'Contitech',
      category: 'POWERTRAIN',
      oemRefs: [],
      crossRefs: [],
      unit: 'adet',
      packSize: 1,
      status: 'ACTIVE',
      source: 'MOCK',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      partId: 'PM-005',
      sku: 'MOTOR-OIL-5W30',
      name: 'Motor Yağı 5W30',
      brand: 'Castrol',
      category: 'POWERTRAIN',
      oemRefs: [],
      crossRefs: ['SHELL-5W30', 'MOBIL-5W30'],
      unit: 'litre',
      packSize: 5,
      status: 'ACTIVE',
      source: 'MOCK',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
  ],
  
  suppliers: [
    {
      supplierId: 'SUPP-001',
      name: 'Brembo Tedarik',
      type: 'DISTRIBUTOR',
      country: 'İtalya',
      avgLeadDays: 5,
      reliabilityScore: 95,
      status: 'ACTIVE',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      supplierId: 'SUPP-002',
      name: 'Mann Filter',
      type: 'MANUFACTURER',
      country: 'Almanya',
      avgLeadDays: 7,
      reliabilityScore: 92,
      status: 'ACTIVE',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      supplierId: 'SUPP-003',
      name: 'B2B Parça Ağı',
      type: 'B2B_NETWORK',
      avgLeadDays: 3,
      reliabilityScore: 85,
      status: 'ACTIVE',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
  ],
  
  edges: [
    {
      edgeId: 'EDGE-001',
      supplierId: 'SUPP-001',
      partId: 'PM-001',
      supplierSku: 'BREMBO-FP-EU-001',
      unitPrice: 850,
      currency: 'TRY',
      minOrderQty: 1,
      leadDays: 5,
      active: true,
      lastUpdated: new Date().toISOString(),
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      edgeId: 'EDGE-002',
      supplierId: 'SUPP-002',
      partId: 'PM-002',
      supplierSku: 'MANN-OF-TRY-001',
      unitPrice: 350,
      currency: 'TRY',
      minOrderQty: 5,
      leadDays: 7,
      active: true,
      lastUpdated: new Date().toISOString(),
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
  ],
  
  inventory: [
    {
      inventoryId: 'INV-001',
      partId: 'PM-001',
      warehouseId: 'WH-ISTANBUL',
      onHand: 15,
      reserved: 2,
      inTransit: 0,
      safetyStock: 5,
      unitCost: 850,
      totalValue: 12750,
      status: 'GOOD',
      updatedAt: new Date().toISOString(),
    },
    {
      inventoryId: 'INV-002',
      partId: 'PM-002',
      warehouseId: 'WH-ISTANBUL',
      onHand: 45,
      reserved: 5,
      inTransit: 10,
      safetyStock: 10,
      unitCost: 350,
      totalValue: 15750,
      status: 'GOOD',
      updatedAt: new Date().toISOString(),
    },
    {
      inventoryId: 'INV-003',
      partId: 'PM-003',
      warehouseId: 'WH-ISTANBUL',
      onHand: 8,
      reserved: 1,
      inTransit: 0,
      safetyStock: 3,
      unitCost: 280,
      totalValue: 2240,
      status: 'GOOD',
      updatedAt: new Date().toISOString(),
    },
    {
      inventoryId: 'INV-004',
      partId: 'PM-004',
      warehouseId: 'WH-ISTANBUL',
      onHand: 2,
      reserved: 0,
      inTransit: 0,
      safetyStock: 3,
      unitCost: 4500,
      totalValue: 9000,
      status: 'AGING',
      lastMovedDate: '2026-01-15',
      updatedAt: new Date().toISOString(),
    },
    {
      inventoryId: 'INV-005',
      partId: 'PM-005',
      warehouseId: 'WH-ISTANBUL',
      onHand: 120,
      reserved: 20,
      inTransit: 50,
      safetyStock: 30,
      unitCost: 85,
      totalValue: 10200,
      status: 'GOOD',
      updatedAt: new Date().toISOString(),
    },
  ],
  
  salesSignals: [
    {
      signalId: 'SIGNAL-001',
      partId: 'PM-001',
      period: 'D30',
      soldQty: 120,
      soldValue: 102000,
      avgPrice: 850,
      dailyAverage: 4,
      weeklyTrend: 'STABLE',
      marginPercent: 25,
      deadStockRisk: 0,
      forecastStock: 3.75,
      generatedAt: new Date().toISOString(),
      source: 'MOCK',
    },
    {
      signalId: 'SIGNAL-002',
      partId: 'PM-002',
      period: 'D30',
      soldQty: 90,
      soldValue: 31500,
      avgPrice: 350,
      dailyAverage: 3,
      weeklyTrend: 'UP',
      marginPercent: 28,
      deadStockRisk: 0,
      forecastStock: 15,
      generatedAt: new Date().toISOString(),
      source: 'MOCK',
    },
    {
      signalId: 'SIGNAL-003',
      partId: 'PM-003',
      period: 'D30',
      soldQty: 30,
      soldValue: 8400,
      avgPrice: 280,
      dailyAverage: 1,
      weeklyTrend: 'STABLE',
      marginPercent: 30,
      deadStockRisk: 10,
      forecastStock: 8,
      generatedAt: new Date().toISOString(),
      source: 'MOCK',
    },
    {
      signalId: 'SIGNAL-004',
      partId: 'PM-004',
      period: 'D30',
      soldQty: 5,
      soldValue: 31000,
      avgPrice: 6200,
      dailyAverage: 0.17,
      weeklyTrend: 'DOWN',
      marginPercent: 35,
      deadStockRisk: 80,
      forecastStock: 400,
      generatedAt: new Date().toISOString(),
      source: 'MOCK',
    },
    {
      signalId: 'SIGNAL-005',
      partId: 'PM-005',
      period: 'D30',
      soldQty: 400,
      soldValue: 48000,
      avgPrice: 120,
      dailyAverage: 13.3,
      weeklyTrend: 'UP',
      marginPercent: 40,
      deadStockRisk: 0,
      forecastStock: 9,
      generatedAt: new Date().toISOString(),
      source: 'MOCK',
    },
  ],
  
  priceSignals: [
    {
      signalId: 'PRICE-001',
      partId: 'PM-001',
      lastUnitPrice: 850,
      avgPrice30d: 845,
      volatilityPercent: 2,
      trend: 'STABLE',
      masked: false,
      lastUpdated: new Date().toISOString(),
      currency: 'TRY',
    },
    {
      signalId: 'PRICE-002',
      partId: 'PM-002',
      lastUnitPrice: 350,
      avgPrice30d: 348,
      volatilityPercent: 1,
      trend: 'UP',
      masked: false,
      lastUpdated: new Date().toISOString(),
      currency: 'TRY',
    },
  ],
  
  categories: [
    {
      categoryId: 'CAT-BRAKE',
      name: 'BRAKE',
      description: 'Fren sistemi parçaları',
      partCount: 10,
      totalStockValue: 25000,
    },
    {
      categoryId: 'CAT-POWERTRAIN',
      name: 'POWERTRAIN',
      description: 'İtme sistemi',
      partCount: 20,
      totalStockValue: 85000,
    },
    {
      categoryId: 'CAT-ELECTRONIC',
      name: 'ELECTRONIC',
      description: 'Elektronik bileşenler',
      partCount: 15,
      totalStockValue: 45000,
    },
  ],
  
  mappings: {
    oemCrossRefs: [
      {
        refId: 'REF-001',
        oem: 'BMW-34-25-6-761-671',
        aftermarketId: 'PM-001',
        aftermarketSku: 'BRAKE-FP-001',
        confidence: 100,
      },
    ],
    fitments: [
      {
        fitmentId: 'FIT-001',
        partId: 'PM-001',
        vehiclePlatform: 'BMW_F30_2012_2018',
        engineTypes: ['N20', 'N26'],
      },
    ],
  },
  
  summary: {
    totalParts: 5,
    totalSuppliers: 3,
    totalStockValue: 49940,
    totalOnHand: 190,
    criticalStockCount: 1,
    deadStockCount: 1,
    avgTurnover30d: 129,
  },
};

// ========== OEM CROSS-REFERENCE MAPPING ==========

/**
 * OemCrossReference: OEM ↔ Aftermarket eşleştirme motoru
 * Gerçek OEM numarası ile aftermarket alternatifleri eşler
 * Deterministic mapping - quality_grade ve compatibility_score bazlı
 */
export interface OemCrossReference {
  id: string;
  
  // OEM tarafı
  oem_part_number: string;      // Örn: 7701208177 (Renault)
  brand: string;                // OEM marka (Renault, VW, BMW, etc)
  part_master_id: string;       // PM-XXXX reference
  
  // Aftermarket tarafı
  aftermarket_brand: string;
  aftermarket_part_number: string;
  
  // Scoring
  quality_grade: 'OEM' | 'OES' | 'AFTERMARKET_A' | 'AFTERMARKET_B';
  compatibility_score: number;  // 0-100
  
  // Metadata
  source: 'MANUAL' | 'FEED' | 'IMPORT';
  created_at: string;
  updated_at: string;
}

