export enum GraphQueryType {
  NODE_LOOKUP = 'NODE_LOOKUP',
  NEIGHBORHOOD_TRAVERSAL = 'NEIGHBORHOOD_TRAVERSAL',
  TEMPORAL_CHAIN_QUERY = 'TEMPORAL_CHAIN_QUERY',
  LINEAGE_TRACE_QUERY = 'LINEAGE_TRACE_QUERY',
  INTELLIGENCE_DISCOVERY_QUERY = 'INTELLIGENCE_DISCOVERY_QUERY',
  TRUST_AWARE_QUERY = 'TRUST_AWARE_QUERY',
}
