/**
 * Data Engine Identity Binding Result
 *
 * Output of identity binding evaluation.
 * Represents the deterministic binding decision and complete reasoning.
 */

import type { DataEngineBindingStatus } from '../types/DataEngineBindingStatus';
import type { DataEngineBindingIssue } from './DataEngineBindingIssue';
import type { DataEngineIdentityBindingPolicy } from './DataEngineIdentityBindingPolicy';

/**
 * Identity Binding Result model.
 *
 * Produced by evaluateIdentityBinding().
 * Fully describes the identity binding decision, issues, and reasoning.
 *
 * Design principle:
 * The result is complete, auditable, and deterministic.
 * All decision factors are visible; no hidden logic.
 * Downstream systems can trust this result as the authoritative binding outcome.
 */
export interface DataEngineIdentityBindingResult {
  /**
   * Binding decision status.
   * The final determination of whether this feed can be bound to its identity context.
   */
  readonly status: DataEngineBindingStatus;

  /**
   * Issues encountered during binding evaluation.
   * Empty array = no issues (status likely BOUND).
   * Non-empty array = issues exist (may affect binding outcome based on severity and policy).
   */
  readonly issues: DataEngineBindingIssue[];

  /**
   * Reference to the evaluated binding candidate.
   * Links this result back to the input for traceability.
   */
  readonly candidateId: string;

  /**
   * Reference to the original intake candidate (Phase 2).
   * Enables full audit trail from intake through binding.
   */
  readonly intakeCandidateId: string;

  /**
   * Binding envelope reference (optional).
   * If binding is accepted and envelope is created for downstream use,
   * reference that envelope here.
   *
   * Not generated by binding layer; provided by downstream system if applicable.
   * Example: 'env_bound_20260311_001'
   */
  readonly bindingEnvelopeRef?: string;

  /**
   * Policy applied during evaluation.
   * The exact policy used to make this binding decision.
   * Enables auditing, policy version tracking, and decision reproducibility.
   */
  readonly policyApplied: DataEngineIdentityBindingPolicy;

  /**
   * Whether binding has operational limitations.
   * - true: BOUND_WITH_LIMITATIONS is the status; flag is explicit in status, for clarity
   * - false: Other statuses apply (BOUND, REJECTED, UNRESOLVED, QUARANTINED)
   *
   * Useful for systems that bifurcate on "can use but with restrictions" vs hard outcomes.
   */
  readonly hasLimitations: boolean;

  /**
   * Description of specific limitations (optional).
   * If hasLimitations is true, explains what the limitations are.
   *
   * Examples:
   * - "Identity context incomplete; federated binding path cannot be fully validated"
   * - "Low-trust identity source; binding permitted but requires downstream caution"
   * - "Multiple ambiguous identity context fields; manual review recommended"
   */
  readonly limitationDescription?: string;

  /**
   * Human-readable decision summary.
   * Brief explanation of the binding decision and key reasoning.
   *
   * Examples:
   * - "Feed bound; identity context is complete and trustworthy"
   * - "Feed bound with limitations; identity valid but federation context incomplete"
   * - "Feed rejected; identity has been revoked"
   * - "Feed quarantined; issuer context is ambiguous and requires clarification"
   * - "Feed unresolved; identity context lacks minimum fields for binding evaluation"
   */
  readonly decisionSummary: string;

  /**
   * When this evaluation occurred.
   * ISO 8601 UTC timestamp.
   * Enables binding result history and reasoning audit trails.
   */
  readonly evaluatedAt: string;

  /**
   * Identity bindings characteristics (informational).
   * Summary of the identity characteristics found during evaluation.
   *
   * Examples:
   * - { trustLevel: 'MEDIUM', issuer: 'SERVICE_CENTER_001', scope: 'authorized-dealers' }
   * - { trustLevel: 'LOW', federationComplete: false }
   *
   * Useful for logging, metrics, and downstream operational awareness.
   */
  readonly identityCharacteristics?: {
    readonly trustLevel?: string;
    readonly issuer?: string;
    readonly scope?: string;
    readonly environment?: string;
    readonly isStale?: boolean;
    readonly isExpired?: boolean;
    readonly isRevoked?: boolean;
    readonly federationComplete?: boolean;
  };
}
