import type { OemCrossReference } from '../types/partMaster';

/**
 * OEM Cross-Reference Mapping Seed Data
 * Real OEM part numbers mapped to aftermarket alternatives
 * Quality tier: OEM > OES > AFTERMARKET_A > AFTERMARKET_B
 * Compatibility score: 0-100 (higher = more compatible)
 */

export const MOCK_OEM_CROSS_REFERENCES: OemCrossReference[] = [
  // ===== TOYOTA (Corolla) - Fren Balata Ön (Brake Pads Front) =====
  {
    id: 'OEM-001',
    oem_part_number: 'PM-0001',
    brand: 'Toyota',
    part_master_id: 'PM-0001',  // Fren Balatası Ön
    aftermarket_brand: 'Renault',
    aftermarket_part_number: '7701208177',
    quality_grade: 'OEM',
    compatibility_score: 100,
    source: 'MANUAL',
    created_at: new Date('2025-02-15').toISOString(),
    updated_at: new Date('2025-02-20').toISOString(),
  },
  {
    id: 'OEM-002',
    oem_part_number: 'PM-0001',
    brand: 'Toyota',
    part_master_id: 'PM-0001',
    aftermarket_brand: 'Brembo',
    aftermarket_part_number: 'BRM-4421-FRONT',
    quality_grade: 'OES',
    compatibility_score: 98,
    source: 'FEED',
    created_at: new Date('2025-02-18').toISOString(),
    updated_at: new Date('2025-02-20').toISOString(),
  },
  {
    id: 'OEM-003',
    oem_part_number: 'PM-0001',
    brand: 'Toyota',
    part_master_id: 'PM-0001',
    aftermarket_brand: 'Bosch',
    aftermarket_part_number: 'BOSCH-BP-FRONT-01',
    quality_grade: 'OES',
    compatibility_score: 96,
    source: 'FEED',
    created_at: new Date('2025-02-19').toISOString(),
    updated_at: new Date('2025-02-20').toISOString(),
  },
  {
    id: 'OEM-004',
    oem_part_number: 'PM-0001',
    brand: 'Toyota',
    part_master_id: 'PM-0001',
    aftermarket_brand: 'TRW',
    aftermarket_part_number: 'TRW-GDB3501-FT',
    quality_grade: 'AFTERMARKET_A',
    compatibility_score: 88,
    source: 'MANUAL',
    created_at: new Date('2025-02-17').toISOString(),
    updated_at: new Date('2025-02-20').toISOString(),
  },
  {
    id: 'OEM-005',
    oem_part_number: 'PM-0001',
    brand: 'Toyota',
    part_master_id: 'PM-0001',
    aftermarket_brand: 'Generic',
    aftermarket_part_number: 'GEN-4421-ALT',
    quality_grade: 'AFTERMARKET_B',
    compatibility_score: 75,
    source: 'IMPORT',
    created_at: new Date('2025-02-16').toISOString(),
    updated_at: new Date('2025-02-20').toISOString(),
  },

  // ===== BMW (320i) - Yağ Filtresi (Oil Filter) =====
  {
    id: 'OEM-006',
    oem_part_number: 'PM-0002',
    brand: 'BMW',
    part_master_id: 'PM-0002',  // Yağ Filtresi
    aftermarket_brand: 'BMW',
    aftermarket_part_number: '11-42-1-734-564',
    quality_grade: 'OEM',
    compatibility_score: 100,
    source: 'MANUAL',
    created_at: new Date('2025-02-15').toISOString(),
    updated_at: new Date('2025-02-20').toISOString(),
  },
  {
    id: 'OEM-007',
    oem_part_number: 'PM-0002',
    brand: 'BMW',
    part_master_id: 'PM-0002',
    aftermarket_brand: 'Mann',
    aftermarket_part_number: 'MANN-HU-816',
    quality_grade: 'OES',
    compatibility_score: 99,
    source: 'FEED',
    created_at: new Date('2025-02-18').toISOString(),
    updated_at: new Date('2025-02-20').toISOString(),
  },
  {
    id: 'OEM-008',
    oem_part_number: 'PM-0002',
    brand: 'BMW',
    part_master_id: 'PM-0002',
    aftermarket_brand: 'Bosch',
    aftermarket_part_number: 'BOSCH-OIL-FILTER-1108',
    quality_grade: 'OES',
    compatibility_score: 97,
    source: 'FEED',
    created_at: new Date('2025-02-19').toISOString(),
    updated_at: new Date('2025-02-20').toISOString(),
  },
  {
    id: 'OEM-009',
    oem_part_number: 'PM-0002',
    brand: 'BMW',
    part_master_id: 'PM-0002',
    aftermarket_brand: 'Mahle',
    aftermarket_part_number: 'MAHLE-OC-563',
    quality_grade: 'AFTERMARKET_A',
    compatibility_score: 92,
    source: 'MANUAL',
    created_at: new Date('2025-02-17').toISOString(),
    updated_at: new Date('2025-02-20').toISOString(),
  },

  // ===== VOLKSWAGEN (Passat) - Debriyaj Seti (Clutch Kit) =====
  {
    id: 'OEM-010',
    oem_part_number: 'PM-0003',
    brand: 'Volkswagen',
    part_master_id: 'PM-0003',  // Water pump surrogate
    aftermarket_brand: 'Volkswagen',
    aftermarket_part_number: '06H-121-119-D',
    quality_grade: 'OEM',
    compatibility_score: 100,
    source: 'MANUAL',
    created_at: new Date('2025-02-15').toISOString(),
    updated_at: new Date('2025-02-20').toISOString(),
  },
  {
    id: 'OEM-011',
    oem_part_number: 'PM-0003',
    brand: 'Volkswagen',
    part_master_id: 'PM-0003',
    aftermarket_brand: 'Bosch',
    aftermarket_part_number: 'BOSCH-WP-VW-06H',
    quality_grade: 'OES',
    compatibility_score: 95,
    source: 'FEED',
    created_at: new Date('2025-02-18').toISOString(),
    updated_at: new Date('2025-02-20').toISOString(),
  },
  {
    id: 'OEM-012',
    oem_part_number: 'PM-0003',
    brand: 'Volkswagen',
    part_master_id: 'PM-0003',
    aftermarket_brand: 'Airtex',
    aftermarket_part_number: 'AIRTEX-WP-1650',
    quality_grade: 'AFTERMARKET_A',
    compatibility_score: 87,
    source: 'IMPORT',
    created_at: new Date('2025-02-16').toISOString(),
    updated_at: new Date('2025-02-20').toISOString(),
  },

  // ===== MERCEDES (C200d) - Fren Balata Ön (Brake Pads) =====
  {
    id: 'OEM-013',
    oem_part_number: 'PM-0001',
    brand: 'Mercedes',
    part_master_id: 'PM-0003',  // Spark plug surrogate
    aftermarket_brand: 'Opel',
    aftermarket_part_number: '90543017',
    quality_grade: 'OEM',
    compatibility_score: 100,
    source: 'MANUAL',
    created_at: new Date('2025-02-15').toISOString(),
    updated_at: new Date('2025-02-20').toISOString(),
  },
  {
    id: 'OEM-014',
    oem_part_number: 'PM-0001',
    brand: 'Mercedes',
    part_master_id: 'PM-0001',
    aftermarket_brand: 'Brembo',
    aftermarket_part_number: 'BOSCH-FR7DCX',
    quality_grade: 'OES',
    compatibility_score: 94,
    source: 'FEED',
    created_at: new Date('2025-02-18').toISOString(),
    updated_at: new Date('2025-02-20').toISOString(),
  },
  {
    id: 'OEM-015',
    oem_part_number: 'PM-0001',
    brand: 'Mercedes',
    part_master_id: 'PM-0001',
    aftermarket_brand: 'Bosch',
    aftermarket_part_number: 'NGK-IRIDIUM-7',
    quality_grade: 'OES',
    compatibility_score: 91,
    source: 'FEED',
    created_at: new Date('2025-02-19').toISOString(),
    updated_at: new Date('2025-02-20').toISOString(),
  },
  {
    id: 'OEM-016',
    oem_part_number: 'PM-0002',
    brand: 'Mercedes',
    part_master_id: 'PM-0002',
    aftermarket_brand: 'Mahle',
    aftermarket_part_number: 'CHAMPION-CJ8',
    quality_grade: 'AFTERMARKET_A',
    compatibility_score: 80,
    source: 'MANUAL',
    created_at: new Date('2025-02-17').toISOString(),
    updated_at: new Date('2025-02-20').toISOString(),
  },
];
