/**
 * Data Engine Normalization Issue Codes
 *
 * Specific issue codes encountered during semantic normalization of feed payloads.
 * Issues are categorized by concern type and severity.
 */

export enum DataEngineNormalizationIssueCode {
  // Payload Structure Issues
  MISSING_REQUIRED_FIELD = 'MISSING_REQUIRED_FIELD',
  INVALID_FIELD_TYPE = 'INVALID_FIELD_TYPE',
  MALFORMED_PAYLOAD = 'MALFORMED_PAYLOAD',
  EMPTY_PAYLOAD = 'EMPTY_PAYLOAD',

  // Schema Issues
  UNKNOWN_SCHEMA_VERSION = 'UNKNOWN_SCHEMA_VERSION',
  LEGACY_SCHEMA_VERSION = 'LEGACY_SCHEMA_VERSION',
  SCHEMA_MISMATCH = 'SCHEMA_MISMATCH',

  // Field Value Issues
  INVALID_ENUM_VALUE = 'INVALID_ENUM_VALUE',
  OUT_OF_RANGE_VALUE = 'OUT_OF_RANGE_VALUE',
  INVALID_DATE_FORMAT = 'INVALID_DATE_FORMAT',
  INVALID_IDENTIFIER_FORMAT = 'INVALID_IDENTIFIER_FORMAT',

  // Semantic Mapping Issues
  UNMAPPABLE_CLASSIFICATION = 'UNMAPPABLE_CLASSIFICATION',
  AMBIGUOUS_SOURCE_MAPPING = 'AMBIGUOUS_SOURCE_MAPPING',
  MISSING_CONTEXT_FOR_NORMALIZATION = 'MISSING_CONTEXT_FOR_NORMALIZATION',

  // Validation Issues
  SEMANTIC_VALIDATION_FAILED = 'SEMANTIC_VALIDATION_FAILED',
  CROSS_FIELD_CONSTRAINT_VIOLATION = 'CROSS_FIELD_CONSTRAINT_VIOLATION',

  // Data Quality Issues
  INCOMPLETE_TEMPORAL_DATA = 'INCOMPLETE_TEMPORAL_DATA',
  INCONSISTENT_TIMESTAMPS = 'INCONSISTENT_TIMESTAMPS',
  MISSING_OR_INFERRED_VALUE = 'MISSING_OR_INFERRED_VALUE',
}
