/**
 * Vehicle State Snapshot Store
 * Read-model layer derived from Data Engine events
 * 
 * Design:
 * - Event-sourced: Snapshots updated from events (not primary source)
 * - PII-safe: No VIN, plate, or raw meta
 * - In-memory circular buffer: Latest snapshots per vehicleId
 * - Non-breaking: Existing event pipeline untouched
 * 
 * Usage:
 * - applyDataEngineEventToSnapshot() → triggered by event ingestion
 * - getSnapshot(vehicleId) → read current state
 * - getAllSnapshots() → bulk query
 */

/**
 * Finding item - safely renderable expertise/diagnostics finding
 */
export interface Finding {
  code: string;
  severity: string;
  message: string;
}

/**
 * VehicleState Snapshot - Unified read-model for UI
 * PII-safe representation of vehicle's analytical state
 * 
 * Single Source of Truth for all UI components reading vehicle data.
 * Derived from Data Engine event stream, not primary source.
 */
export type VehicleStateSnapshot = {
  vehicleId: string;
  schemaVersion: "1.0";
  updatedAt: string; // ISO 8601, snapshot-wide

  lastEvent?: {
    eventId: string;
    domain: "risk" | "insurance" | "part" | "expertise" | "service" | "odometer" | "diagnostics" | string;
    eventType: string;
    occurredAt: string;
    source?: string;
  };

  // Risk domain indices (from RISK_INDICES_UPDATED events)
  risk?: {
    indices: Array<{
      key: string;
      value: number;
      confidence?: number;
    }>;
    confidenceAverage?: number;
    lastUpdatedAt?: string;
  };

  // Insurance domain indices (from INSURANCE_INDICES_UPDATED events)
  insurance?: {
    indices: Array<{
      key: string;
      value: number;
      confidence?: number;
    }>;
    lastUpdatedAt?: string;
  };

  // Part domain indices (from PART_INDICES_UPDATED events)
  part?: {
    indices: Array<{
      key: string;
      value: number;
      confidence?: number;
    }>;
    lastUpdatedAt?: string;
  };

  // Expertise domain (from expert reports and findings)
  expertise?: {
    lastReportAt?: string;
    findings?: Finding[];
    lastUpdatedAt?: string;
  };

  // Service records domain
  service?: {
    recordsCount?: number;
    lastServiceAt?: string;
    lastUpdatedAt?: string;
  };

  // Odometer domain
  odometer?: {
    currentKm?: number;
    historyCount?: number;
    status?: "normal" | "anomaly";
    lastUpdatedAt?: string;
  };

  // Diagnostics domain
  diagnostics?: {
    obdCount?: number;
    lastDtcAt?: string;
    lastUpdatedAt?: string;
  };

  // Phase 9.1+: Vehicle Intelligence Summary (from VEHICLE_INTELLIGENCE_AGGREGATED event)
  // Lightweight composite score and coverage metrics
  // Updated by reducer when aggregation event is ingested
  vehicleIntelligenceSummary?: {
    // Composite metrics
    compositeScore?: number;         // 0-100, unified intelligence score
    compositeLevel?: string;         // "low-risk", "medium-risk", "high-risk"
    
    // Domain-specific indices
    trustIndex?: number;             // 0-100, data trustworthiness
    reliabilityIndex?: number;       // 0-100, mechanical reliability
    maintenanceDiscipline?: number;  // 0-100, service history quality
    
    // Risk metrics
    structuralRisk?: number;         // 0-100, damage/wear risk
    mechanicalRisk?: number;         // 0-100, OBD/fault code risk
    insuranceRisk?: number;          // 0-100, claims/correlation risk
    serviceGapScore?: number;        // 0-100, maintenance gaps
    
    // Data quality metrics
    confidence?: number;             // 0-100, analysis confidence
    dataSourceCount?: number;        // Number of data sources used
    analysisTimestamp?: string;      // ISO 8601, when analysis was performed
    
    // Traceability
    lastAggregatedEventId?: string;  // Event ID for traceability
    lastUpdatedAt?: string;          // When snapshot section was updated
    
    // Phase 9.5: Recommendation metadata (calculated by orchestrator)
    recommendationCount?: number;                    // Total recommendations generated
    highSeverityRecommendationCount?: number;       // Count of 'high' severity only
    lastRecommendationsUpdatedAt?: string;          // ISO timestamp when recommendations were last generated
  };

  // Phase 9.4: Vehicle Intelligence Recommendations (generated from summary)
  // Generated by pure recommendation engine based on vehicleIntelligenceSummary
  // Stored async by recommendationOrchestrator, NOT by reducer
  vehicleIntelligenceRecommendations?: Array<{
    key: string;                     // Unique recommendation ID
    title: string;                   // User-facing title (Turkish)
    summary: string;                 // Brief description
    severity: 'high' | 'medium' | 'low';
    rationale?: string[];            // Why this recommendation (for explainability)
  }>;

  // Data sources present in this snapshot
  sources?: {
    present: string[];
  };
};

/**
 * In-memory snapshot store (Map<vehicleId, VehicleStateSnapshot>)
 */
const snapshotStore = new Map<string, VehicleStateSnapshot>();

/**
 * Initialize or get existing snapshot for a vehicle
 */
function initializeSnapshot(vehicleId: string): VehicleStateSnapshot {
  if (snapshotStore.has(vehicleId)) {
    return snapshotStore.get(vehicleId)!;
  }

  const snapshot: VehicleStateSnapshot = {
    vehicleId,
    schemaVersion: "1.0",
    updatedAt: new Date().toISOString(),
  };

  snapshotStore.set(vehicleId, snapshot);
  return snapshot;
}

/**
 * Compute confidence average from indices
 */
function computeConfidenceAverage(
  indices: Array<{ confidence?: number }>
): number | undefined {
  const confidences = indices
    .map((idx) => idx.confidence)
    .filter((c) => typeof c === 'number' && c >= 0) as number[];

  if (confidences.length === 0) {
    return undefined;
  }

  return Math.round((confidences.reduce((a, b) => a + b, 0) / confidences.length) * 100) / 100;
}

/**
 * Get current snapshot for a vehicle
 */
export function getSnapshot(vehicleId: string): VehicleStateSnapshot | null {
  return snapshotStore.get(vehicleId) || null;
}

/**
 * Get all snapshots
 */
export function getAllSnapshots(): VehicleStateSnapshot[] {
  return Array.from(snapshotStore.values());
}

/**
 * Upsert snapshot (merge with existing)
 * Used by reducer when applying events
 */
export function upsertSnapshot(
  vehicleId: string,
  partial: Partial<VehicleStateSnapshot>
): VehicleStateSnapshot {
  const snapshot = initializeSnapshot(vehicleId);

  // Merge partial update
  const updated: VehicleStateSnapshot = {
    ...snapshot,
    ...partial,
    vehicleId, // Always preserve vehicleId
    schemaVersion: "1.0", // Always latest schema
    updatedAt: partial.updatedAt || new Date().toISOString(),
  };

  snapshotStore.set(vehicleId, updated);

  if (import.meta.env.DEV) {
    console.debug('[VehicleStateSnapshotStore] Snapshot upserted:', {
      vehicleId,
      domains: [
        updated.risk ? 'risk' : null,
        updated.insurance ? 'insurance' : null,
        updated.part ? 'part' : null,
      ].filter(Boolean),
      updatedAt: updated.updatedAt,
    });
  }

  return updated;
}

/**
 * Clear all snapshots (DEV only)
 */
export function clearSnapshots(): void {
  if (!import.meta.env.DEV) {
    console.warn('[VehicleStateSnapshotStore] clearSnapshots() is DEV-only');
    return;
  }

  snapshotStore.clear();

  if (import.meta.env.DEV) {
    console.debug('[VehicleStateSnapshotStore] All snapshots cleared');
  }
}

/**
 * Get snapshot statistics (DEV only)
 */
export function getSnapshotStats(): {
  totalSnapshots: number;
  vehicleIds: string[];
} {
  return {
    totalSnapshots: snapshotStore.size,
    vehicleIds: Array.from(snapshotStore.keys()),
  };
}
