/**
 * Data Engine Feed Candidate
 *
 * Represents incoming feed data at the intake boundary.
 *
 * A candidate is NOT yet an accepted feed envelope.
 * It represents raw incoming data that has NOT yet passed intake evaluation.
 *
 * The candidate structure allows for partial/incomplete incoming data
 * while maintaining source and identity context for evaluation.
 */

import type { DataSourceType } from '../../types/DataSourceType';
import type { DataEngineTimestampModel } from '../../models/DataEngineTimestampModel';
import type { FeedMetadataStructure } from '../../metadata/FeedMetadataStructure';

/**
 * Feed Candidate structure.
 *
 * Represents incoming feed data before intake evaluation and acceptance.
 *
 * Key principle:
 * This structure legitimately allows partial/incomplete data because it
 * represents "what arrived at the intake boundary" - not yet a trusted,
 * accepted feed envelope.
 *
 * Once accepted by evaluateFeedIntake(), the candidate becomes a
 * DataEngineFeedEnvelope for downstream processing.
 */
export interface DataEngineFeedCandidate {
  /**
   * Candidate identifier.
   * Uniquely identifies this candidate in the intake system.
   * Generated by the intake source system, not the Data Engine.
   *
   * Example: 'cand_20260311_001a8f9e'
   */
  readonly candidateId: string;

  /**
   * When this candidate arrived at the intake boundary.
   * ISO 8601 UTC timestamp.
   * Recorded by the intake system, not derived from the candidate itself.
   */
  readonly candidateTimestamp: string;

  /**
   * Source system classification.
   * Type of system providing this candidate.
   * Required for source-aware intake policy evaluation.
   */
  readonly sourceOrigin: DataSourceType;

  /**
   * Identity linkage identifier (optional).
   * If present, provides the identityId for this candidate.
   * Required field for acceptance; missing identityId is a critical intake issue.
   *
   * May be absent in a candidate (which becomes an intake issue),
   * but must be present for acceptance.
   */
  readonly identityId?: string;

  /**
   * Candidate payload data.
   * The actual intelligence data from source system.
   * May be complete, partial, or malformed.
   *
   * Optional because malformed candidates may arrive at the boundary.
   * Missing or empty payload triggers intake issues.
   */
  readonly candidatePayload?: Record<string, unknown>;

  /**
   * Metadata structure (optional).
   * Metadata about the feed itself.
   * May be partial or incomplete.
   *
   * Optional because not all sources provide complete metadata.
   */
  readonly metadata?: Partial<FeedMetadataStructure>;

  /**
   * Timestamp structure (optional).
   * Temporal information about events.
   * May be partial, malformed, or missing.
   *
   * Optional because timestamp quality varies by source.
   */
  readonly timestamps?: Partial<DataEngineTimestampModel>;
}
